apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-kibana
  labels:
    app: payment-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-kibana
  template:
    metadata:
      labels:
        app: payment-kibana
        version: $IMAGE_TAG
    spec:
      containers:
      - name: payment-kibana
        image: uttapong/payment-kibana:$IMAGE_TAG
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
