apiVersion: v1
kind: Service
metadata:
  name: payment-kibana
  labels:
    app: payment-kibana
spec:
  selector:
    app: payment-kibana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
